# Generated by Django 2.1.4 on 2019-02-04 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_history', '0002_auto_20190202_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='debt',
            name='percent',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='debt_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
