# Generated by Django 2.1.4 on 2019-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_history', '0003_auto_20190204_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
